### ISSUE TITLE
ProfileComponent did not save after update?

### ISSUE THREAD

**Issue by martinym28** [santoshdahal2016/laravel-vue-vuetify-dashboard-template#1]
This template code is clearly for developing. Good job.
as title, ProfileComponent did not **save** after update?
Also at app.js the import errorHandler from './helper/errorHandler'; has notice:
'errorHandler' is declared but its value is never read.ts(6133)

**Comment by santoshdahal2016** [comment]
https://github.com/santoshdahal2016/laravel-vue-vuetify-dashboard-template/commit/c5f0d68947392f47a2c8d11a48299302fd6ed5b6
